################################################################################
# Pool Controller Home Assistant (PCHA)
# Extrait à fusionner dans /config/configuration.yaml
#
# Entrées
#   /config/packages/
#   pool-controller-ha/dashboard/piscine.yaml
#
# Sorties
#   Chargement des packages PCHA
#   Tableau de bord pcha-validation
################################################################################

homeassistant:
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named pool-controller-ha/themes

lovelace:
  dashboards:
    pcha-validation:
      mode: yaml
      filename: pool-controller-ha/dashboard/piscine.yaml
      title: PCHA Validation
      icon: mdi:pool
      show_in_sidebar: true
